# Site settings
title: Seed
email: dev@praekeltfoundation.org
description: >
  What is seed
baseurl: "/seed"
url: "http://praekeltfoundation.github.io"
fixedNav: 'true' # true or false
theme: grey # green, blue, orange, purple, grey
twitterUsername: praekeltfound
githubUsername: praekeltfoundation
dribbbleUsername:
codepenUsername:

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
categories: [documentation]
